package-lock.json
package.json
src/App.js
src/__tests__/contexts/FormWrapper.test.js
src/__tests__/contexts/TableWrapper.test.js
src/components/DemoTable.js
src/contexts/FormWrapper.js
src/contexts/TableWrapper.js
src/mocks/handlers.js
src/react-radfish/index.js
src/react-radfish/table/index.js

Adds a `DemoForm` with building block components exported from `react-radfish`
1. Form should be sortable on client. Sort by pressing each column header
2. Form should pull data dynamically from API/MSW endpoint
3. API endpoint should support query parameters to filter data shown on form
https://github.com/NMFS-RADFish/boilerplate/assets/35090461/65926561-f72a-47d7-9078-6ee6f947d5bb
Need to still add unit tests

[RADFISH-51] Table component

---

src/components/DemoTable.js
src/contexts/TableWrapper.js
src/mocks/handlers.js
src/react-radfish/table/index.js
src/react-radfish/table/style.css

Add an onClick handler to each table row. Adds a code comment to document it.
This can be useful for redirecting the user from the table to some sort of detail view.
Will add more detailed docs in future PR.

[RADFISH-51] TableRow component onClick handler

---

README.md

Adds documentation around how to respond to an offline request using MSW and store into the form data locally.

Add offline handler documentation

---

src/components/DemoForm.js

Use `e.preventDefault()` in `onOfflineSubmit` click handler to prevent duplicate entries from being submitted.

Create onOfflineSubmit click handler to prevent duplicate form submittal

---

package-lock.json
src/__tests__/contexts/TableWrapper.test.js
src/components/DemoTable.js
src/components/Layout.js
src/contexts/TableWrapper.js
src/react-radfish/inputs/style.css
src/react-radfish/table/index.js
src/react-radfish/table/style.css

Created four table pagination components:
* Button navigation
* Page count (i.e. Page 1 of 100)
* Go-to page input
* Display number of rows select
Added the components to `DemoTable` to display how it can be used.
Screenshot:

[RADFISH-66] Table Pagination

---

README.md
src/__tests__/config/config.test.js
src/__tests__/contexts/FormWrapper.test.js
src/components/DemoForm.js
src/config/form.js
src/contexts/FormWrapper.js
src/utilities/computedValues.js
src/utilities/index.js
src/utilities/inputVisibility.js

Creates a pattern to build a complex form, where values from certain fields can control the value and visibility of other form inputs.
Steps to create these dependencies:
User story: As a developer, I want the `fullName` field to control the visibility of `nickname` field. `nickname` field should only be visible when the `fullName` field has text.
1. In `config/form.js` add `fullName` and `nickname` constants.
2. Create both inputs in `DemoForm.js`. Ensure that you are using the constant values defined in step 1 and also that `fullName` has the `linkedInputIds={[nickname]}` property. This will indicate that `nickname` is dependent on `fullName`
For example:
```
<Label htmlFor={fullName}>Full Name</Label>
<TextInput
id={fullName}
name={fullName}
type="text"
placeholder="Full Name" …
```

Configurable form flows

---

.github/workflows/run-tests.yml

This adds an additional step to the GitHub Actions runner to install native bindings for Rollup.
https://github.com/NMFS-RADFish/boilerplate/actions/runs/8395953403/job/22999973284

Add linux dependencies to test automation pipeline

---

.env.example
README.md
src/__tests__/storage/IndexedDBMethod.test.js
src/contexts/FormWrapper.jsx
src/hooks/useOfflineStorage.js
src/mocks/handlers.js
src/pages/ComplexForm.example.jsx
src/pages/MultiStepForm.example.jsx
src/pages/Table.example.jsx
src/storage/IndexedDBMethod.js
src/storage/StorageMethod.js
src/storage/StorageModel.js

* Replace localStorage with IndexedDB for offline storage
* Refactor `IndexedDBMethod` to enable developers to create multiple tables

[RADFish-114] Replace localStorage with IndexedDB

---

.env.test
README.md
src/App.jsx
src/__tests__/contexts/FormWrapper.test.jsx
src/__tests__/storage/IndexedDBMethod.test.js
src/contexts/FormWrapper.jsx
src/hooks/useMultiStepForm.js
src/hooks/useOfflineStorage.js
src/mocks/handlers.js
src/pages/ComplexForm.example.jsx
src/pages/MultiStepForm.example.jsx
src/storage/IndexedDBMethod.js
src/storage/StorageMethod.js
src/storage/StorageModel.js

This PR includes the following changes:
* Save the species list to indexedDB
* Fetch species list from indexedDB when offline
* Fix data errors when navigating from an existing form entry on the table page to the form details on the complex form page

RADFISH-112 cache species list

---

README.md

Adds initial file structure documentation to README
Keep in mind this doesn't include breaking out files into `packages` directory. Felt like this wasn't the right time to do this since we have a bunch of open PRs. If we decide we want to do this, I can do it first thing after these PRs get merged.

[RADFISH-110] Add initial file structure documentation

---

src/components/HeaderNav.jsx

When navigating with mobile nav, on navigation to a new route, the sidebar should close.

Sidebar should close on navigate

---

src/contexts/FormWrapper.example.jsx
src/pages/ComplexForm.example.jsx

All Form submissions will be saved as isDraft: true in IndexedDB when offline, and will be saved in IndexDB as isDraft: false when online.

RADFISH-142: Set is draft is true/false

---

src/App.jsx
src/__tests__/components/Toast.test.jsx
src/components/HeaderNav.jsx
src/components/ServerSync.jsx
src/hooks/useOfflineStatus.js
src/hooks/useOfflineStorage.example.js
src/hooks/useToast.js
src/mocks/handlers.js
src/packages/react-components/alerts/index.jsx
src/pages/ComplexForm.example.jsx
src/pages/Table.example.jsx

Integrate slimmed down version of https://github.com/NMFS-RADFish/boilerplate/pull/72 into `boilerplate`
https://github.com/NMFS-RADFish/boilerplate/assets/35090461/a80ef72e-d63b-4d0a-bcdc-0ccdc542b69b
Toast seems to be not working as expected. I will open up a separate PR with a few improvements as well.

Create ServerSync component, break out useOfflineStatus into hook

---

examples/simple-form/package-lock.json
examples/simple-form/src/App.jsx
examples/simple-form/src/contexts/FormWrapper.jsx
examples/simple-form/src/pages/Form.jsx

Refactor `simple-form` example to use `FormWrapper`

Simple form with form wrapper

---

examples/simple-table/README.md
examples/simple-table/package-lock.json
examples/simple-table/src/App.jsx
examples/simple-table/src/index.jsx
examples/simple-table/src/packages/contexts/TableWrapper.jsx

* Refactored `TableWrapper` context provider to only manage state.
* Abstracted out the column creation to be on the same level where `TableWrapper` is imported (`index.jsx`).
* Moved `TableWrapper` to `packages` directory so that it can be eventually moved to the npm react-radfish package.
* Created docs on how to setup the table.

RADFISH-193 Simple Table Updates

---

examples/network-status/README.md

Create `README.md` file that outlines the steps for configuring network status detection w/ toast message alert.

RADFISHS-196 Network Status Example Docs

---

examples/on-device-storage/README.md

* Add `useOfflineStorage` methods to docs
* Add example use-cases

RADFISH-202 Update On-Device Storage Docs

---

examples/simple-form/README.md
examples/simple-form/src/pages/Form.jsx

* Replace `a` tag with trussworks `Link` component
* Create `README.md` docs

RADFISH-195 Simple Form Example Updates

---

examples/server-sync/src/components/ServerSync.jsx
packages/react-radfish/index.js
packages/react-radfish/spinner/index.jsx
packages/react-radfish/spinner/style.css

Adds a `Spinner` component to illustrate an asynchronous action.
This will require a version bump of the component library, and a republish to npm.
https://github.com/NMFS-RADFish/boilerplate/assets/35090461/8272a019-5973-4b16-9ebc-34d29b852605

Add Spinner component to component library

---

examples/multistep-form/src/config/common.js

Removes unused config files. Artifact from `main` example

Remove unused common config

---

examples/network-status/src/App.jsx
packages/react-radfish/Application/index.jsx
packages/react-radfish/hooks/index.js
packages/react-radfish/hooks/useOfflineStatus.js
packages/react-radfish/hooks/useToast/useToast.js
packages/react-radfish/hooks/useToast/useToast.spec.js
packages/react-radfish/index.js
packages/react-radfish/jest.config.js
packages/react-radfish/package.json
packages/react-radfish/vite.config.js

- Add network status toast to global application component
- Set default toast duration to 2 seconds
- Refactor network status hook to use a single function

Add global toast with network status

---

examples/field-validators/src/App.jsx
examples/field-validators/src/index.jsx
examples/field-validators/src/pages/Form.jsx

Noting that we don't have form validation documentation in docusaurus.

RADFISH-220: Field Validator Updates

---

examples/simple-table/src/App.jsx
examples/simple-table/src/index.jsx
packages/react-radfish/table/index.jsx

Makes some updates to the Simple Table implementation to include a submit handler, new Toast implementation, and Image field within the table.
https://github.com/NMFS-RADFish/boilerplate/assets/35090461/4393774d-de48-453d-a2e0-2b8373434d93

RADFISH-227: Simple Table updates

---

examples/conditional-form-fields/src/App.jsx
examples/field-validators/src/App.jsx
examples/mock-api/src/App.jsx
examples/on-device-storage/src/App.jsx
examples/persisted-form/src/App.jsx
examples/simple-table/src/App.jsx

Changing backticks to code blocks

Radfish 17 passover presentation layer

---

examples/computed-form-fields/src/index.jsx
examples/conditional-form-fields/src/index.jsx
examples/field-validators/src/index.jsx
examples/main/package-lock.json
examples/main/package.json
examples/main/src/index.jsx
examples/mock-api/src/index.jsx
examples/multistep-form/src/index.jsx
examples/network-status/src/index.jsx
examples/on-device-storage/src/index.jsx
examples/persisted-form/src/index.jsx
examples/server-sync/src/index.jsx
examples/simple-table/src/index.jsx
package-lock.json
packages/react-radfish/ErrorBoundary/index.jsx
packages/react-radfish/index.js

Implement error boundary on all examples

Error Boundary

---

package-lock.json
packages/react-radfish/.prettierrc
packages/react-radfish/Application/index.jsx
packages/react-radfish/hooks/index.js
packages/react-radfish/hooks/useOfflineStatus/useOfflineStatus.js
packages/react-radfish/hooks/useOfflineStatus/useOfflineStatus.spec.js
packages/react-radfish/hooks/useToast/useToast.js
packages/react-radfish/hooks/useToast/useToast.spec.js
packages/react-radfish/package.json

- Add tests for offline and toast hooks
- Refactor hooks and expose application provider
- Fix issue where main Application component would rerender every second
Offline banner stays at top of application while application is offline to make it clear that the device has no network connection.

Update global toast state

---

templates/react-javascript/mocks/browser.js
templates/react-javascript/mocks/handlers.js
templates/react-javascript/package-lock.json
templates/react-javascript/package.json
templates/react-javascript/src/App.jsx
templates/react-javascript/src/index.jsx

- Resize radfish logo
- Fix offline handler
- Add Application container

Update javascript template

---

README.md

Updated wording to reflect current examples as suggested here:
https://apps-st.fisheries.noaa.gov/jira/browse/RADFISH-248

Radfish 248 - Updated demoform to examples/ 

---

examples/main/package.json
examples/mock-api/package.json
examples/multistep-form/package.json
examples/network-status/package.json
examples/on-device-storage/package.json
examples/persisted-form/package.json
examples/react-query/package.json
examples/server-sync/package.json
examples/simple-table/package.json
templates/react-javascript/package-lock.json
templates/react-javascript/package.json
templates/react-javascript/public/mockServiceWorker.js

Resolves #175
Additionally bumped example versions.
**Changes**
- Update examples and templates to recieve all 0.x versions of radfish packages
- Update dependencies

Update react-javascript template dependencies

---

README.md
examples/computed-form-fields/README.md
examples/computed-form-fields/src/App.jsx
examples/computed-form-fields/src/pages/Form.jsx
examples/conditional-form-fields/README.md
examples/conditional-form-fields/src/App.jsx
examples/field-validators/README.md
examples/field-validators/src/App.jsx
examples/main/README.md
examples/main/src/config/common.js
examples/mock-api/README.md
examples/mock-api/src/App.jsx
examples/multistep-form/README.md
examples/multistep-form/src/App.jsx
examples/network-status/README.md
examples/network-status/src/App.jsx
examples/on-device-storage/README.md
examples/on-device-storage/src/App.jsx
examples/persisted-form/README.md
examples/persisted-form/src/App.jsx
examples/react-query/README.md
examples/react-query/src/App.jsx
examples/server-sync/README.md
examples/server-sync/src/App.jsx
examples/simple-table/README.md
examples/simple-table/src/App.jsx
templates/react-javascript/src/pages/Home.jsx

- fix broken links
- remove console.logs

Fix broken links from new path merge

---

packages/react-radfish/DatePicker/DatePicker.spec.jsx
packages/react-radfish/DatePicker/index.jsx

Working PR for Jesse datepicker updates

Date picker updates

---

packages/react-radfish/table/Table.spec.jsx
packages/react-radfish/table/index.jsx

issues #210 and #211 
- Added fixes for `totalRows` and `onPageChange`
- Added unit tests

210 and 211 table -  totalrows should default to length of data provided

---

packages/radfish/README.md
packages/react-radfish/README.md

issue #193 
related to: https://github.com/NMFS-RADFish/cli/pull/23
- Created ReadMes for `react` and `react-radfish` packages, then added npm version badges

193 add badges to readmes

---

examples/simple-table/README.md

issue [#127](https://github.com/orgs/NMFS-RADFish/projects/2/views/2?filterQuery=status%3ATodo%2C%22In+Progress%22%2C%22Needs+Review%22%2CDone+assignee%3Ajaygiang&pane=issue&itemId=82657562&issue=NMFS-RADFish%7Cradfish%7C127)
- Fix broken link
- Added official documentation link so that it's uniform with the other example ReadMes

Fix broken link

---

examples/react-query/package.json
examples/react-query/public/mockServiceWorker.js
examples/react-query/src/App.jsx

- **Bump vite-plugin-pwa from 0.19.2 to 0.20.5 in /examples/react-query**
- **Bump jsdom from 24.0.0 to 25.0.1 in /examples/react-query**
- **Bump @trussworks/react-uswds in /examples/react-query**
- **Bump vitest from 1.4.0 to 2.1.2 in /examples/react-query**

Update react-query example dependencies

---

examples/field-validators/package.json

This is to go along with the dependabot updates for this example.

Update field validator example to use latest RADFish libraries

---

examples/computed-form-fields/package.json
examples/computed-form-fields/public/mockServiceWorker.js

This pull request updates the computed fields example to include the latest version of the RADFish packages.

Update RADFish dependencies for computed fields example

---

packages/react-radfish/table/index.jsx

issue #369 
- Adds `area-label` to `<Icon>` component

Simple Table 508 Compliance Warning

---

packages/react-radfish/Application/index.jsx

issue #410 
- Use `useRef` hook to track previous offline state

410 -  Should not show "Application is Online" notification on initial render

---

examples/computed-form-fields/README.md
examples/computed-form-fields/src/pages/Home.jsx
examples/conditional-form-fields/README.md
examples/conditional-form-fields/src/App.jsx
examples/conditional-form-fields/src/pages/Home.jsx

Issue #524 subtask of #515
- Capitalized constant variables that have string values
- Created functions to handle onChange updates
- Add heading syntax to each step so that it shows up in docusarus sidebar
- Add comments in code snippet
- Update some content
- Update some content and formatting

524 polish conditional form fields example

---

examples/form-structure/README.md
examples/form-structure/src/pages/Home.jsx

Issue #530 subtask of #515
- Applied prettier format
- Updated readme to match format of other examples(e.g Steps)
- Add heading syntax to each step so that it shows up in docusarus sidebar
- Update some content

530 - Polish form structure example

---

examples/mock-api/README.md
examples/mock-api/src/App.jsx
examples/mock-api/src/index.jsx
examples/mock-api/src/mocks/handlers.js
examples/mock-api/src/pages/Home.jsx
examples/mock-api/src/styles/theme.css

Issue #532 subtask of #515 
- Add heading syntax to each step so that it shows up in docusarus sidebar
- Add comments in code snippet
- Update some content
- Remove extra font-family Arial Narrow font

532 - Polish mock-api Example

---

.github/workflows/run-tests.yml
templates/react-javascript/.gitignore
templates/react-javascript/lighthouserc.json
templates/react-javascript/vite.config.js

- Run lighthouse against production builds
- Only upload lighthouse reports as part of GitHub CI

Update lighthouse checks

---

examples/network-status/README.md

Issue #540 subtask of #515 
- Small updates to readme

540 - Polish network status

---

examples/on-device-storage/README.md
examples/on-device-storage/src/pages/Home.jsx

Issue #542 subtask of #515 
- Add headings to steps in readme
- Remove not necessary comment

542 - Polish on device storage

---

examples/simple-table/README.md

Issue #585 subtask of #515 
- Format readme sub-headers to match other example readmes

585 polish simple table example

---

examples/persisted-form/README.md
examples/persisted-form/src/App.jsx
examples/persisted-form/src/pages/Home.jsx

Issue #543 subtask #515 
- Add headings to titles
- Fix update indexedDB error
- Add toast to submission handle
https://github.com/user-attachments/assets/f317389e-a645-435c-ac6f-5d5bbd2631a4

544 - Polish persisted form example

---

examples/computed-form-fields/README.md
examples/conditional-form-fields/README.md
examples/field-validators/README.md
examples/form-structure/README.md
examples/mock-api/README.md
examples/multistep-form/README.md
examples/network-status/README.md
examples/on-device-storage/README.md
examples/persisted-form/README.md
examples/react-query/README.md
examples/server-sync/README.md
examples/simple-table/README.md

These changes close #164 https://github.com/NMFS-RADFish/radfish/issues/164 
Branch and commit message referencing 167 are typos.

Editorial scrub for issue #164
