NMFS-RADFish/boilerplate

- src/hooks/useMultiStepForm.js
- src/pages/MultiStepForm.example.jsx
- src/storage/IndexedDBMethod.js
This bug ticket fixes a few issues reported by Steve in Google Chat:
Changes:
1. Multistep form `Button` components that progress step, but do not submit form need to be assigned a `type="button"` prop, else they we submit the form by default.
2. When updating cached data via indexDB `update` method, we need to pass an array of data objects, rather than a single data object, since we are using `bulkUpdate` under the hood for performance reasons.
3. Adds missing import of `FormGroup` that got lost during a merge to main, this was causing the multistep to break and render a WSOD
I'm not sure what he means by "allows user to enter any page number to navigate to non-exsistent pages". I will try to follow up in Google chat directly
> Bug: MultiStep form incorrectly submitting and caching data

- src/pages/MultiStepForm.example.jsx
Buttons within forms that should not submit formData, should have `type="button"` prop.
> init multi step should not submit form

- src/App.jsx
- src/__tests__/components/Toast.test.jsx
- src/hooks/useToast.js
- src/packages/react-components/alerts/index.jsx
- src/pages/ComplexForm.example.jsx
- src/pages/Table.example.jsx
Refactors the Toast implementation for the following reasons:
1. Lift out configuration from `react-radfish` package into application code (developer will need to change this)
2. Add additional `Alert` types
3. Create reusable hooks for `useOfflineStatus` and `useToast` to make the code a bit cleaner and DRY.
> Refactor toast implementation to be more extensible

- examples/computed-fields/package.json
- examples/dynamic-form/package.json
- examples/field-validators/package.json
- examples/multistep-form/package.json
- examples/network-status/package.json
- examples/on-device-storage/package.json
- examples/server-sync/package.json
- examples/simple-form/package.json
- examples/simple-table/package.json
This is needed in order for the latest version `0.9.0` to be shown across all example UIs.
> Update version number across examples

- examples/simple-table/src/App.jsx
- packages/react-radfish/table/index.jsx
Adds a default sort icon to make it more clear that these columns are sortable by click. Also makes some corrections to components that no longer exist in `react-radfish` to come from `trussworks`
Note that this will require a patched release of the component library to be published.
https://github.com/NMFS-RADFish/boilerplate/assets/35090461/fb6c95b1-1edb-46b5-8436-697f05e276e7
> Add default sort icon for clarity of sortability

- examples/field-validators/src/pages/Form.jsx
Problem: Validation is showing up in three different ways- Validation message should be under the label, not above
Solution: Move error right below label
> RADFISH-126: Fix error labeling

- examples/on-device-storage/src/App.jsx
Updates title copy to inform user to only test offline refreshing after a production build has been done.
> RADFISH-224: On-Device Storage updates

- packages/react-radfish/hooks/useToast/useToast.js
- packages/react-radfish/hooks/useToast/useToast.spec.js
The `dispatchToast` should be exported directly from the package instead of from the hook. There was a previous intermediary implementation that relied on the dispatcher needing access to the react state, but that isn't the case anymore.
> Move dispatch toast method outside of react hook

- package-lock.json
- packages/react-radfish/Application/index.jsx
- packages/react-radfish/hooks/useToast/useToast.js
- packages/react-radfish/hooks/useToast/useToast.spec.js
- packages/react-radfish/package.json
The `useToasts` hook doesn't export dispatchToast method anymore, and the import should be coming from the hooks module.
> Fix dispatchToast reference in Application component

- packages/radfish/on-device-storage/storage/IndexedDBMethod.js
- packages/react-radfish/OfflineStorage/index.jsx
Changes:
* Throw errors if the incorrect data type is passed to one of the methods from `useOfflineStorage`
* Expose `storageMethod` in the `useOfflineStorage` context hook. This allows a developer to access all [Dexie.js APIs](https://dexie.org/docs/API-Reference)
```
const { storageMethod } = useOfflineStorage();
storageMethod.db.formData.toCollection().count(); // show the count of items in the database
```
Testing:
1. In root directory run: `npm run build`
2. In `examples/on-device-storage` directory remove `"@nmfs-radfish/radfish": "^0.2.2"` and 
`"@nmfs-radfish/react-radfish": "^0.4.11"`. Then run: `npm install`
3. Use the newly exposed `storageMethod` in `App.jsx`
4. Start project: `npm start`
> RADFISH-175 & RADFISH-237 dexie error handling

- examples/computed-form-fields/README.md
- examples/conditional-form-fields/README.md
- examples/field-validators/README.md
- examples/main/README.md
- examples/mock-api/README.md
- examples/multistep-form/README.md
- examples/network-status/README.md
- examples/on-device-storage/README.md
- examples/persisted-form/README.md
- examples/server-sync/README.md
- examples/simple-table/README.md
This makes some tweaks to the READMEs in the boilerplate to link to the examples in docusaurus.
> Link README to examples docusaurus

- examples/computed-form-fields/README.md
- examples/conditional-form-fields/README.md
- examples/field-validators/README.md
- examples/main/README.md
- examples/mock-api/README.md
- examples/multistep-form/README.md
- examples/network-status/README.md
- examples/on-device-storage/README.md
- examples/persisted-form/README.md
- examples/server-sync/README.md
- examples/simple-table/README.md
[RADFISH-246](https://apps-st.fisheries.noaa.gov/jira/secure/RapidBoard.jspa?rapidView=856&projectKey=RADFISH&view=planning&selectedIssue=RADFISH-246&issueLimit=100) (Issue is the 3rd bullet point) 
Each README.md has a broken link "Learn more about RADFish examples at the official [documentation](https://nmfs-radfish.github.io/documentation/docs/examples/templates_examples)"
Changed to correct url: https://nmfs-radfish.github.io/documentation/docs/building-your-application/templates_examples
> RADFISH-246: Fix Broken Links

- README.md
- [GitHub]( https://github.com/NMFS-RADFish/documentation/issues/29)
- [Jira](https://apps-st.fisheries.noaa.gov/jira/secure/RapidBoard.jspa?rapidView=856&projectKey=RADFISH&view=planning&selectedIssue=RADFISH-263&issueLimit=100)
- Update README to provide puppeteer with vitest example
- Remove Jest accessibility testing in README
> RADFISH - 263 Remove references to Jest since we are using Vitest

- examples/on-device-storage/README.md
- examples/server-sync/README.md
Fixed syntax of code snippets to prevent them from breaking `docusaurus-plugin-remote-content` when processing `README.md` files.
> 85 docs   fix syntax error in on device storage readmemd

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/pull_request_templated.md
Fixes #191 and #192  
- Created yml templates for Bugs and Feature
- I commented out `checkboxes` secition. Lmk if you would like to activate it
- Created md template for Pull Request
- The current format for PR Title is `RADFish - [Component]: [Brief description of the change] (#IssueNumber)`. Please let me know if you would like any updates to it. 
Note: We won't be able to see these changes until this PR is merged
> RADFish - GH Template: Create templates for Bug, Feature and PR (#191)

- packages/react-radfish/table/Table.spec.jsx
- packages/react-radfish/table/index.jsx
There was a conditional check on pagination options that would fallback to unsorted data.
- Changed the data assignment to use `sortedData` instead of `data` when pagination options are not provided.
> Fix table sorting when pagination options are not provided

- packages/react-radfish/table/Table.spec.jsx
The node-style import was having issues resolving the ErrorBoundary component in the Table tests.
> Fix ErrorBoundary import in table test

- examples/server-sync/package.json
- **Bump vite-plugin-pwa from 0.19.2 to 0.20.5 in /examples/server-sync**
- **Bump @trussworks/react-uswds in /examples/server-sync**
- **Bump jsdom from 24.0.0 to 25.0.1 in /examples/server-sync**
- **Bump @testing-library/user-event in /examples/server-sync**
- **Bump vitest from 1.4.0 to 2.1.2 in /examples/server-sync**
> Update server sync example dependencies

- examples/persisted-form/package.json
- **Bump vite-plugin-pwa from 0.19.2 to 0.20.5 in /examples/persisted-form**
- **Bump @trussworks/react-uswds in /examples/persisted-form**
- **Bump jsdom from 24.0.0 to 25.0.1 in /examples/persisted-form**
- **Bump @testing-library/user-event in /examples/persisted-form**
- **Bump vitest from 1.4.0 to 2.1.2 in /examples/persisted-form**
> Update persisted form example dependencies

- examples/simple-table/package.json
- **Bump vite-plugin-pwa from 0.19.2 to 0.20.5 in /examples/simple-table**
- **Bump @trussworks/react-uswds in /examples/simple-table**
- **Bump jsdom from 24.0.0 to 25.0.1 in /examples/simple-table**
- **Bump @testing-library/user-event in /examples/simple-table**
- **Bump vitest from 1.4.0 to 2.1.2 in /examples/simple-table**
> Update simple table example dependencies

- examples/network-status/package.json
- **Bump vite-plugin-pwa from 0.19.2 to 0.20.5 in /examples/network-status**
- **Bump @trussworks/react-uswds in /examples/network-status**
- **Bump jsdom from 24.0.0 to 25.0.1 in /examples/network-status**
- **Bump @testing-library/user-event in /examples/network-status**
- **Bump vitest from 1.4.0 to 2.1.2 in /examples/network-status**
> Update network status example dependencies

- examples/multistep-form/package.json
- **Bump vite-plugin-pwa from 0.19.2 to 0.20.5 in /examples/multistep-form**
- **Bump @trussworks/react-uswds in /examples/multistep-form**
- **Bump jsdom from 24.0.0 to 25.0.1 in /examples/multistep-form**
- **Bump @testing-library/user-event in /examples/multistep-form**
- **Bump vitest from 1.4.0 to 2.1.2 in /examples/multistep-form**
> Update multistep form fields example dependencies

- examples/mock-api/package.json
- **Bump vite-plugin-pwa from 0.19.2 to 0.20.5 in /examples/mock api**
- **Bump @trussworks/react-uswds in /examples/mock api**
- **Bump jsdom from 24.0.0 to 25.0.1 in /examples/mock api**
- **Bump @testing-library/user-event in /examples/mock api**
- **Bump vitest from 1.4.0 to 2.1.2 in /examples/mock api**
> Update mock api example dependencies

- examples/field-validators/package.json
- **Bump vite-plugin-pwa from 0.19.2 to 0.20.5 in /examples/field-validators**
- **Bump @trussworks/react-uswds in /examples/field-validators**
- **Bump jsdom from 24.0.0 to 25.0.1 in /examples/field-validators**
- **Bump @testing-library/user-event in /examples/field-validators**
- **Bump vitest from 1.4.0 to 2.1.2 in /examples/field-validators**
> Update field validators example dependencies

- examples/conditional-form-fields/package.json
- **Bump vite-plugin-pwa from 0.19.2 to 0.20.5 in /examples/conditional-form-fields**
- **Bump @trussworks/react-uswds in /examples/conditional-form-fields**
- **Bump jsdom from 24.0.0 to 25.0.1 in /examples/conditional-form-fields**
- **Bump @testing-library/user-event in /examples/conditional-form-fields**
- **Bump vitest from 1.4.0 to 2.1.2 in /examples/conditional-form-fields**
> Update conditional form fields example dependencies

- packages/react-radfish/spinner/index.jsx
issue #371 
Change to `className` in `Spinner` component
> Simple Table - className error on spinner component

- .github/dependabot.yml
The schedule is being updated to run on Thrusday instead of Monday. This should give more time to address package updates before weekly releases are scheduled to go out.
Additionally, relaxed Dependabot to only check for minor patch updates. This should reduce the amount of pull requests that are opened each week.
> Update Dependabot checks

- .github/workflows/run-tests.yml
- templates/react-javascript/lighthouserc.json
#368 
- Add back `lighthousesrc.json`
- Add back workflow steps but with template path
> Add back lighthouse workflow but for template steps

- templates/react-javascript/package-lock.json
The package lock wasn't updated in the last release, so creating a project through the CLI was not receiving the changes from the [latest release](https://github.com/NMFS-RADFish/boilerplate/releases/tag/0.20.0).
> Bump template dependencies to latest patched versions

- examples/computed-form-fields/README.md
- examples/conditional-form-fields/README.md
- examples/field-validators/README.md
- examples/form-structure/README.md
- examples/mock-api/README.md
- examples/multistep-form/README.md
- examples/network-status/README.md
- examples/on-device-storage/README.md
- examples/persisted-form/README.md
- examples/react-query/README.md
- examples/server-sync/README.md
- examples/simple-table/README.md
Updated header to keep in side nav and updated text to describe image.
> 442 Remove double headers in example READMEs

- examples/network-status/README.md
issue #525 
- Remove toast example from readme
- Show how to extract `isOffline` from `useOfflineStatus`
> 525 - Docs: Network Status Example missing key detail

- examples/simple-table/src/pages/Home.jsx
- packages/react-radfish/table/index.jsx
#673 
• Calculates maximum possible pages based on total rows and page size                                                                                   
• Ensures page index stays within valid bounds (between 0 and maxPage-1)
> 673 - Fix table out of bounds

- packages/radfish/index.js
- packages/radfish/package.json
- templates/react-javascript/package-lock.json
Accidentally, included some debugging code in the 1.1.0 release that was referencing a `weatherSurvey` store.
Probably should probably add a linter check to help prevent these types of errors from making it into the main branch.
> Remove debug code

- packages/react-radfish/table/index.jsx
#695 
This PR fixes an issue where Table pagination buttons trigger form submission when the `Table` component is rendered inside a form element.
When a `Table `component with pagination controls is rendered inside a form, clicking on the pagination buttons causes the form to submit. This happens because the Button components in the pagination controls don't have an explicit type attribute, so they default to `type="submit"`.
Added `type="button"`to all pagination Button components in the `Table` component to prevent unintended form submissions.
> 695 - Bug Table pagination buttons trigger form submission 

- .github/workflows/publish-radfish.yml
- .github/workflows/publish-react-radfish.yml
- .github/workflows/run-tests.yml
- package-lock.json
- packages/radfish/babel.config.js
- packages/radfish/jest.config.js
- packages/radfish/package.json
- packages/radfish/storage/Collection.spec.js
- packages/radfish/storage/Connector.spec.js
- packages/radfish/storage/Store.spec.js
- packages/react-radfish/package.json
This PR allows anyone with admin repo access to publish `@nmfs-radfish/radfish` and `@nmfs-radfish/react-radfish` packages to NPM.
Simplified @nmfs-radfish/radfish package's test dependencies by migrating from Jest → Vitest. The ESM update from #691 fixed running tests from downstream applications, but caused issues when running the packages own test suite.
Also resolves #685.
When workflows require the:
- release type (major, minor, patch)
- whether or not it's a prerelease
This helps to determine the tags that will be created and updated when pushing to both npm and github.
Additionally, a GitHub release will be drafted to reference the [package]@[version] tag.
> Add GitHub Actions for publishing packages to NPM registry

- .github/workflows/publish-radfish.yml
- .github/workflows/publish-react-radfish.yml
- .github/workflows/run-tests.yml
Bumped the Nodejs version to 20 in runners since 18 is no longer being maintained.
Removed `--legacy-peer-deps` flag from tests because it doesn't resolve an underlying uswds dependency correctly.
> chore: Bump nodejs version in runners to v20
